build:
  image: python:2.7
  tags:
    - linux
  script:
    - apt-get update
    - apt-get install -y upx
    - pip install pyinstaller
    - python -OO -m PyInstaller --strip --onefile registry-image-check.py
    - mv dist/registry-image-check .
  artifacts:
     paths:
      - registry-image-check
